name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths:
      - '*.js'
      - 'wwwroot/*'

  pull_request:
    branches: [ "master" ]
    paths:
      - '*.js'
      - 'wwwroot/*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ridomin/iothubux:latest
    - name: Login to Docker
      uses: docker/login-action@v1
      with:
        username: ridomin
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: push image
      run: docker push ridomin/iothubux:latest
